spring.application.name=AcademiX
server.port=8083

# Local PostgreSQL Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/academixdb
spring.datasource.username=postgres
spring.datasource.password=52020278522
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jmx.enabled=false