spring.application.name=AcademiX
server.port=8083

spring.datasource.url=jdbc:postgresql://db-postgresql-fra1-45924-do-user-30646546-0.a.db.ondigitalocean.com:25060/defaultdb?sslmode=require
spring.datasource.username=doadmin
spring.datasource.password=AVNS_xldVkkEBnEgeJLjG8VK
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false
